name: workflow vite
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install nodejs
        uses: actions/setup-node@v4
      - name: fetch repository
        uses: actions/checkout@v4
      - name: configure cache
        uses: actions/cache@v4
        id: npm-cache 
        with:
          path: ./
          key: ${{ runner.os }}-node-${{ hashFiles('./package-lock.json') }}
      - name: install dependencies
        working-directory: ./
        run: npm ci --cache install ./npm --prefer-offline
        
