name: workflow with vite
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: fetch repository
        uses: actions/checkout@v4
      - name: install nodejs
        uses: actions/setup-node@v4
      - name: install dependencies
        run: |
          pwd
          ls
          npm install
