name: workflow with vite
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install nodejs
        uses: actions/setup-node@v4
      - name: fetch repository
        uses: actions/checkout@v4
      - name: configure cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          path: ~/.npm
      - name: install dependencies
        run: npm ci --cache install .npm --prefer-offline
        
